os:
  - linux
dist: trusty
sudo: required
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - curl
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH=`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - export PATH=`pwd`/flutter/bin:$PATH
  - flutter doctor
install:
  - gem install coveralls-lcov
  - pub global activate pana
script: make
after_success:
  - make pana
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache