language: dart
dart:
  - stable
install:
  - gem install coveralls-lcov
  - pub global activate pana
script: make
after_success:
  - make pana
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info