name: flutter_parse
description: Plugin for managing and accessing Parse Server for Dart VM and Flutter.
version: 1.0.1
homepage: https://github.com/eyro-labs/flutter_parse

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_parse_storage_interface: ^1.0.2
  http: ^0.13.3
  meta: ^1.7.0
  uuid: ^3.0.5
  web_socket_channel: ^2.1.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
