name: flutter_parse
description: Plugin for managing and accessing Parse Server for Dart VM and Flutter.
version: 0.2.4
author: Eyro Labs <maulana@cubeacon.com>
homepage: https://github.com/eyro-labs/flutter_parse

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  meta: ^1.1.7
  path: ^1.6.0
  platform: ^2.2.1
  shared_preferences: ^0.5.6+1
  web_socket_channel: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.2.0
