name: flutter_parse
description: Plugin for managing and accessing Parse Server for Dart VM and Flutter.
version: 0.2.4
homepage: https://github.com/eyro-labs/flutter_parse

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  http: ^0.13.1
  meta: ^1.3.0
  path: ^1.8.0
  platform: ^3.0.0
  shared_preferences: ^2.0.5
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
