name: flutter_parse
description: Plugin for managing and accessing Parse Server for Dart VM and Flutter.
version: 0.2.4
homepage: https://github.com/eyro-labs/flutter_parse

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  web_socket_channel: ^2.0.0
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
